(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.CyberShieldCopilot=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){"use strict";
const SAMPLE=`// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract Vault {
    mapping(address => uint256) public balances;

    function withdraw() external {
        uint256 amount = balances[msg.sender];
        (bool sent,) = msg.sender.call{value: amount}("");
        require(sent, "transfer failed");
        balances[msg.sender] = 0;
    }
}`;
const BUNDLE={id:"CSA-Vault-SWC107-v1",source_name:"Vault.sol",source_sha256:"d455a23a5cc3dbb62a6f9646a262822eb5f576438e254dc9d0d30ead57f360d9",analyzers:[{name:"slither",status:"succeeded",finding_count:1},{name:"mythril",status:"succeeded",finding_count:1},{name:"solhint",status:"succeeded",finding_count:1}],findings:[{analyzer:"slither",rule_id:"SWC-107",title:"Reentrancy",severity:"high",description:"External call occurs before the sender balance is cleared.",line:9},{analyzer:"mythril",rule_id:"SWC-107",title:"State change after external call",severity:"medium",description:"A caller can regain control before the state update completes.",line:11},{analyzer:"solhint",rule_id:"avoid-low-level-calls",title:"Avoid low-level calls",severity:"low",description:"Low-level call usage requires explicit defensive handling.",line:9}],consensus:[{id:"SWC-107",title:"Reentrancy",severity:"high",confidence:.7083,analyzers:["slither","mythril"],lines:"9–11",description:"An external value call occurs before the sender balance is cleared."},{id:"avoid-low-level-calls",title:"Avoid low-level calls",severity:"low",confidence:.6667,analyzers:["solhint"],lines:"9",description:"The low-level value call requires explicit defensive handling."}]};
const GUIDANCE={"SWC-107":["Apply Checks–Effects–Interactions: clear or reduce the sender balance before the external value call.","Add an independently reviewed reentrancy guard where cross-function re-entry remains possible.","Add an attacker fallback test that attempts recursive withdrawal and asserts the vault balance cannot be drained.","Re-run Slither, Mythril and Solhint after the change and compare the new evidence bundle."],"avoid-low-level-calls":["Check the low-level call result and document why the call is required.","Prefer a narrowly scoped transfer abstraction where appropriate and test failure handling."]};
function softmax(values){const m=Math.max(...values),e=values.map(v=>Math.exp(v-m)),s=e.reduce((a,b)=>a+b,0);return e.map(v=>v/s)}function features(f){const sev={critical:1,high:.75,medium:.5,low:.25,informational:.1}[f.severity]||0;return[sev,f.confidence,Math.min(f.analyzers.length/3,1),f.lines?1:0,f.id==="SWC-107"?1:0,/access/i.test(f.title)?1:0,/unchecked|low-level/i.test(f.title)?1:0]}function infer(model,finding){const x=features(finding),logits=model.classes.map((_,k)=>model.bias[k]+model.weights[k].reduce((s,w,j)=>s+w*x[j],0)),probs=softmax(logits),winner=probs.indexOf(Math.max(...probs)),contributions=model.feature_names.map((name,j)=>({name,value:x[j],contribution:model.weights[winner][j]*x[j]})).filter(x=>x.value>0).sort((a,b)=>Math.abs(b.contribution)-Math.abs(a.contribution));return{action:model.classes[winner],probability:probs[winner],probabilities:Object.fromEntries(model.classes.map((c,i)=>[c,probs[i]])),features:x,contributions}}function buildContext(bundle){return bundle.consensus.map(f=>({canonical_id:f.id,title:f.title,severity:f.severity,confidence:f.confidence,contributing_analyzers:[...f.analyzers],source_lines:f.lines,deterministic_description:f.description}))}function run(model,bundle=BUNDLE){const before=JSON.stringify(bundle),primary=bundle.consensus[0],prediction=infer(model,primary),context=buildContext(bundle),explanation=`The bounded priority model classifies ${primary.id} as ${prediction.action} (${(prediction.probability*100).toFixed(1)}%). The interpretation is grounded in a ${primary.severity}-severity finding, ${(primary.confidence*100).toFixed(2)}% consensus confidence, ${primary.analyzers.length} contributing analyzers and precise source lines ${primary.lines}. Recursive control can return to withdraw() before balances[msg.sender] is cleared, so repeated withdrawal remains feasible under the reported precondition.`;if(JSON.stringify(bundle)!==before)throw new Error("AI boundary violation: analyzer evidence mutated");return{evidence_context:context,prediction,explanation,guidance:GUIDANCE[primary.id],scope:"The model prioritizes verified evidence and explains feature influence. It does not detect vulnerabilities, modify analyzer findings, generate a patch, or certify the contract.",evidence_unchanged:true}}return{SAMPLE,BUNDLE,GUIDANCE,features,infer,buildContext,run};});
